word_list = [
    'membership',
    'fellowship',
    'merch',
    'give referrals',
    'scholarships',
    'application',
    'internships',
    'shop',
    'international',
    'RTC',
    'deadline',
    'time',
    'postgrad',
    'reapply',
    'housing',
    'requirements',
    'mentor',
    'what RTC',
    'join',
    'who member',
    'access',
    'guidelines',
    'student',
    'free',
    'senior undergraduate',
    'current fellow',
    'partner',
    'paid',
    'secured internship',
    'participate',
    'time off',
    'referral portal',
    'guidelines',
    'eligiblity'
]

keys = [
    'fellowship',
    'membership',
    'time',
    'postgrad',
    'international',
    'internships',
    'housing',
    'requirements',
    'merch',
    'give referrals',
    'mentor',
    'what RTC',
    'scholarships',
    'join',
    'who member',
    'guidelines',
    'application',
    'senior undergraduate',
    'reapply',
    'current fellow',
    'partner',
    'paid',
    'secured internship',
    'time off',
    'referral portal'
]

responses = {
    'fellowship': 'Applications for the RTC Fellowship will open up on April 1, 2021.',
    'fellowship time': 'The fellowship is 12 months long. Fellows must reapply if they would like to continue into the following year.',
    'fellowship participation': 'This fellowship is designed to work around all of your academics and support you while you are at your universities. RTC will provide fellows with opportunities for virtual interactions and in-person events as well as educational programs and internship search assistance throughout the academic year.',
    'membership': 'All you have to do is sign up and then join our Facebook Group. Any current college woman with a passion for technology can sign up.',
    'postgrad fellow': 'Women pursuing their master\'s degree in a tech related area such as Computer Science, Engineering, and Data Science may apply to be a fellow.',
    'senior fellow': 'RISING seniors can apply to become a fellow. The student must still be a student in the upcoming fall semester.',
    'international fellow': 'Any student enrolled in a U.S. or Canadian college can apply to become a fellow. All other students can register to become a member.',
    'current fellow reapply': 'Current fellows DO need to reapply. This is mostly in order to obtain up-to-date information that we can provide our company partners such as new skills, interests, resume, etc. The reapplication is a more streamlined version for the convenience of our Fellows.',
    'internship fellow': 'Although we cannot guarantee internship placement with RTC partners, we work hard to make sure our fellows\' resumes are seen by our partners and that all students have equal access. We highly recommend that fellows use ALL resources available to them to secure a summer internship/permanent job, including participation in RTC recruiting events.',
    'paid internship partner': 'All RTC fellows will be paid the same amount they would be if they secured the internship by other means.',
    'secured internship fellow': 'Fellows can have already secured an internship and/or job. We just ask that fellows report the company, city, title, and start/end date to us for summer program planning purposes.',
    'housing': 'RTC does not provide housing but helps connect women who will be in the same city so that they can work together to locate housing.',
    'merch': 'Check out our shop at https://www.etsy.com/shop/rewritingthecode and represent RTC.',
    'referral portal': 'We closed the portal in June since some students shared the link outside of RTC. It is reopened as of August 1st, 2020, but if you share access to the portal or any information about the people who are offering referrals to anyone outside of this group you will be removed from RTC, no exceptions. You must fill out the following form to agree to the terms of the Referral Portal and get a password to enter the portal: https://airtable.com/shrpKA0gwgVM4rJmK. Once you fill out the form, you can access the portal using the password you\'re given: https://airtable.com/shr2Id8xa9osOrd4Q',
    'give referral': 'To give referrals you can share your information and specifications for how you want RTC women to contact you here: https://airtable.com/shrpqius0dsASxD5Q',
    'guidelines': 'We urge you to read the full RTC Professional Etiquette Guide here: https://tinyurl.com/RTCProfessionalEtiquetteGuide before you reach out to anyone in RTC or external to make sure that you\'re not accidentally being unprofessional and hurting your chances for various opportunities.',
    'scholarships': 'The RTC Scholarship Fund funds educational scholarships for women at risk of being unable to return to school due to financial hardship as a result of COVID-19. Scholarships will be awarded by August 15th to give students time to pay their tuition before the fall term begins.',
    'scholarship requirements': 'To be eligible for scholarships, they have to be members and fellows of Rewriting the Code as of July 1, 2020, women enrolled at U.S. based colleges or universities (2 or 4-year institutions), women starting their second to final year of undergraduate education in Fall 2020, and women majoring in Computer Science, Information Science, Engineering, or Math/Stat majors related to pursuing a career in tech.',
    'international scholarships': 'If you are an international student who currently attends a college in the United States and are facing financial difficulties due to COVID-19, you are now eligible!',
    'default': 'We currently don\'t have information on your question. Please email contact@rewritingthecode.org and we will get back to you.'
} 